//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelfirstApproach
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookInventory
    {
        public int Id { get; set; }
        public string Price { get; set; }
        public string Quantity { get; set; }
        public int BookId { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
