//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class EStock
{
    public int sid { get; set; }
    public string pname { get; set; }
    public Nullable<int> squantity { get; set; }
    public Nullable<int> pid { get; set; }
}
